// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDza7e2ezTBI4f7ceYJqkyyCbxC9Ehtqkk',
    appId: '1:530155243967:web:dfc7f64c139344f570f90a',
    messagingSenderId: '530155243967',
    projectId: 'whatsapp-clone-19dcc',
    authDomain: 'whatsapp-clone-19dcc.firebaseapp.com',
    storageBucket: 'whatsapp-clone-19dcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNH_QBNR_g-ZmLplt9RyG3DzSt_z2k8I',
    appId: '1:530155243967:android:3ddae78d73e7292f70f90a',
    messagingSenderId: '530155243967',
    projectId: 'whatsapp-clone-19dcc',
    storageBucket: 'whatsapp-clone-19dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KrkPo-lijInb4xgVvG2wdYToC-Wt9Us',
    appId: '1:530155243967:ios:4fe0ef13a58b953b70f90a',
    messagingSenderId: '530155243967',
    projectId: 'whatsapp-clone-19dcc',
    storageBucket: 'whatsapp-clone-19dcc.appspot.com',
    iosClientId: '530155243967-2nngl8fqgmskhooknbqtnts268iha1v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KrkPo-lijInb4xgVvG2wdYToC-Wt9Us',
    appId: '1:530155243967:ios:e0fb81738a02cdc170f90a',
    messagingSenderId: '530155243967',
    projectId: 'whatsapp-clone-19dcc',
    storageBucket: 'whatsapp-clone-19dcc.appspot.com',
    iosClientId: '530155243967-kbbopmusttt3f6hnqk0rj62c40bof21p.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
